<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXd8x3PD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXd8x3PD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXd8x3PD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXd8x3PD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXd8x3PD\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xd8x3PD',
    'container.build_id' => '9be829ff',
    'container.build_time' => 1641413913,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXd8x3PD');
